name: 3rd-level-domains
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       S_CHANNEL: ${{ secrets.SLACK_CN_SOLO }}
       S_URL: https://slack.com/api/files.upload
       KNOCKPY_CONFIG: ${{ secrets.KNOCKPY_CONFIG_VT_API }}
jobs:
 subdomains:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget -q $HOST/third-level-domains.txt
         sudo apt-get install python3-setuptools;
         wget -q -i requirements/subdomain-enum.txt; mv findomain-linux findomain; unzip amass_linux_amd64.zip; tar -xzvf subfinder_2.4.7_linux_amd64.tar.gz;
         go env -w GOPATH=~/Downloads;
         go get -u github.com/tomnomnom/assetfinder;
         cp ~/Downloads/bin/assetfinder .; 
         git clone https://github.com/aboul3la/Sublist3r.git
         pip3 install -r Sublist3r/requirements.txt
         chmod +x subs.sh
         for domain in $(cat third-level-domains.txt); do ./subs.sh "$domain"; done
      - name: Output
        if: always()
        run: |
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Recursive-3rd -F file=@recursive-subdomains.txt;

         
         
         

         
