name: 3rd-level-domains
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       S_CHANNEL: ${{ secrets.SLACK_CN_SOLO }}
jobs:
 subdomains:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget -q $HOST/recursive-bruteforce.txt
         sudo apt-get install python3-setuptools;
         wget -q -i requirements/subdomain-enum.txt; mv findomain-linux findomain; unzip amass_linux_amd64.zip; tar -xzvf subfinder_2.4.7_linux_amd64.tar.gz;
         go env -w GOPATH=~/Downloads;
         go get -u github.com/tomnomnom/assetfinder;
         cp ~/Downloads/bin/assetfinder .; 
         git clone https://github.com/aboul3la/Sublist3r.git
         pip3 install -r Sublist3r/requirements.txt
         chmod +x subs.sh
         for domain in $(cat recursive-bruteforce.txt); do ./subs.sh "$domain"; done
#         pip3 install requests==2.25.1
#         git clone https://github.com/m8r0wn/subscraper ; cp requirements/requirements.txt subscraper; cd subscraper; pip3 install -r requirements.txt; sudo python3 setup.py install; cd .. ;
      - name: Output
        if: always()
        run: |
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Recursive -F file=@recursive-subdomains.txt;

         
         
         

         
