name: Aquatone
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      HOST: ${{ secrets.NGROK_URL }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}        
jobs:
  aquatone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/subdomains-live.txt
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
         bash Domain_Monitoring/scripts/aquatone.sh subdomains-live.txt
      - name: Output & Slack Notification
        if: always()
        run: |
          S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Aquatone -F file=@aquatone-output.zip.xz ;
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$S_WEBHOOK" ;


# Aquatone: bash Domain_Monitoring/scripts/aquatone.sh subdomains-live.txt  => aquatone-output.zip.xz
# HTTPX: bash Domain_Monitoring/scripts/httpx.sh subdomains.txt  => httpx.out
# Meg: bash Domain_Monitoring/scripts/meg.sh subdomains-live.txt  => meg-home.zip
# S3Scanner: bash Domain_Monitoring/scripts/s3_scanner.sh subdomains-host.txt  => s3-scan.txt
# DNSgen: bash Domain_Monitoring/scripts/dnsgen.sh subdomains.txt  => dnsgen-wordlist.txt.xz
# FFUF: bash Domain_Monitoring/scripts/ffuf.sh subdomains.txt  => ffuf-output.zip
# Dirsearch: bash Domain_Monitoring/scripts/dirsearch-file.sh subdomains-live.txt => dirsearch-file-reports.zip.xz
# Vhost Scanner: bash Domain_Monitoring/scripts/vhost-scan.sh "$TARGET"  => gobsuter-vhosts.txt
# Subdomain Takevoer: bash Domain_Monitoring/scripts/subdomain_takeover.sh 
# NMAP Full Scan: bash Domain_Monitoring/scripts/nmap-full-scan.sh target-ips.txt  => nmap-vulnerability-scan.txt.xz
# NMAP Top 1000: bash Domain_Monitoring/scripts/nmap-1000-scan.sh ips-live.txt  => nmap-1000-scan.zip
# Httprob: bash Domain_Monitoring/scripts/httprobe.sh subdomains.txt  => httprober.txt
# Nuclei Scan: bash Domain_Monitoring/scripts/nuclei-templat-scan.sh subdomains.txt  => nuclie-scan.out



