name: Amass Bruteforce
on:
  workflow_dispatch:
env:
     TARGET: ${{ secrets.DOMAIN }}
     SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }}
     WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
jobs:
  amass-brute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: | 
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt
         wget --quiet https://github.com/OWASP/Amass/releases/download/v3.11.13/amass_linux_amd64.zip ; unzip amass_linux_amd64.zip
      - name: Amass
        run: |
         ./amass_linux_amd64/amass enum -brute -d "$TARGET" -o amass-brute.txt -rf resolvers.txt
       #./amass_linux_amd64/amass enum -brute -d "$TARGET" -o amass-brute.txt -rf resolvers.txt -max-dns-queries 10000
      - name: Send Output to Slack
        if: always()
        run: |
         xz amass-brute.txt
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Amass-Brute -F file=@amass-brute.txt.xz
      - name: Slack Notification
        if: always()
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"AMASS Brute COMPLETED FOR - '$TARGET'"}' "$WEBHOOK"
