name: Cloud Enum
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      HOST: ${{ secrets.NGROK_URL }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}        
jobs:
  DNSC:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: DNSC
        run: |
         git clone https://github.com/initstring/cloud_enum.git
         cd cloud_enum
         pip3 install -r ./requirements.txt
         python3 cloud_enum.py -k allegro.pl -k allegro -l cloud-enum.txt
         cat buckets.txt
      - name: Send Output to Slack
        if: always()
        run: |
         S_CHANNEL=$(echo $TARGET | sed 's/\./_/g');
         curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=Cloud-Enum -F file=@cloud-enum.txt;
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job *${{ github.job}}* in workflow *${{ github.workflow }}* has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK";
