name: Dev-Test-2

on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN_LARGE_PRIVATE }}
      EXCLUDE_HOST: ${{ secrets.PRI_EXCLUDE_HOST }}
      HOST: ${{ secrets.NGROK_URL }}
      XSS_HUNTER_URL_TOKEN: ${{ secrets.XSS_HUNTER }}
      AWS_CREDS: ${{ secrets.AWS_CREDENTIALS }}
      GIT_USERS: ${{ secrets.TARGET_GITHUB_USERS_LIST }}
      GIT_ORG: ${{ secrets.TARGET_GITHUB_ORG }}
      GIT_TOKEN: ${{ secrets.TOKEN }}
      SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_PRIVATE }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PRIVATE }}
      CURL: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" 
      #SLACK_URL: https://slack.com/api/files.upload

jobs:
  Git-Dorker-Domain:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Slack Test
        run: echo slack_test > slack.txt
      - name: Send Output Files Slack Channel
        if: always()
        run: |
         "$CURL" -F title=Slack-Test -F filename=slack.txt -F file=@slack.txt
        
      #curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Gitdorker-DOMAIN -F filename=git-dorker-domain.csv -F file=@git-dorker-domain_gh_dorks.csv

      

                       
