name: Dev CI
 
on:
  workflow_dispatch:

jobs:
  dev-ci:
    runs-on: ubuntu-latest
    env:
                 TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
                 TARGET_IP: ${{ secrets.TARGET_IP_LIST }}
                 TARGET_IP_EXCLUDE: ${{ secrets.TARGET_IGNORE_IPS_LIST }}
                 CENSYS_API_ID: ${{ secrets.CENSYS_API_ID }}
                 CENSYS_API_SECRET: ${{ secrets.CENSYS_API_SECRET }}
                 SECURITY_TRAILS_API_KEY: ${{ secrets.SECURITY_TRAILS_API_KEY }}
                 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_PRIVATE_BB_CHANNEL_NAME }}  
    
    steps:
      - uses: actions/checkout@v2
                 
      - name: Input Files
        run: |
                 echo "$CENSYS_API_ID" > censys-secrets.txt
                 echo "$CENSYS_API_SECRET" >> censys-secrets.txt
                 curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Dev -F filename=censys-secrets.txt -F file=@censys-secrets.txt
