name: Dev-2
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      AWS_CREDS: ${{ secrets.AWS_CREDENTIALS }}
      HOST: ${{ secrets.NGROK_URL }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}        
jobs:
  s3-teh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget "$HOST"/subdomain.txt
         go env -w GOPATH=~/Downloads;
         go get -u github.com/jaeles-project/jaeles;
         cp ~/Downloads/bin/jaeles .;
         git clone --depth=1 https://github.com/jaeles-project/jaeles-signatures /tmp/jaeles-signatures/
         jaeles config -a reload --signDir /tmp/jaeles-signatures
         ./jaeles scan -c 50 -s /tmp/jaeles-signatures/{cves,common,passive,sensitive} -U subdomain.txt -L 50 -v -G --html jaeles-report
         ls -l

