name: Dev-Test-2

on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       S_CHANNEL: ${{ secrets.SLACK_CN_SOLO }} 
       S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
       S_URL: https://slack.com/api/files.upload

jobs:
#NMAP UDP Full Scan
  nmap-udp-scan:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.workflow }} HAS STARTED - '$TARGET'"}' "$S_WEBHOOK" ;
         sudo apt-get update && sudo apt-get install nmap -y -v
      - name: Nmap UDP scan
        run: sudo nmap -sV -p- -sU -T4 -oA nmap-udp-scan -v $TARGET 
      - name: Output & Slack Notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_"}' "$S_WEBHOOK"
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Nmap-UDP-Scan -F file=@nmap-udp-scan.nmap
         
        
      

      

                       
