name: Dev-Test-2

on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN_LARGE_PRIVATE }}
      EXCLUDE_HOST: ${{ secrets.PRI_EXCLUDE_HOST }}
      HOST: ${{ secrets.NGROK_URL }}
      XSS_HUNTER_URL_TOKEN: ${{ secrets.XSS_HUNTER }}
      AWS_CREDS: ${{ secrets.AWS_CREDENTIALS }}
      GIT_USERS: ${{ secrets.TARGET_GITHUB_USERS_LIST }}
      GIT_ORG: ${{ secrets.TARGET_GITHUB_ORG }}
      GIT_TOKEN: ${{ secrets.TOKEN }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_CHANNEL: ${{ secrets.SLACK_CN_PRIVATE }}
      S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PRIVATE }}
      #CURL: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" 
      SLACK_URL: https://slack.com/api/files.upload

jobs:
  Git-Dorker-Domain:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Slack Test
        run: njnjnj
      - name: Send Output Files Slack Channel
        if: always()
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ gthub.job}} in workflow ${{ github.workflow }} has _*`{{ job.status }}`*_  - '$TARGET'"}' "$S_WEBHOOK"
         
        
      

      

                       
