name: Dev-Test-2

on:
  workflow_dispatch:

jobs:
  ip-host-hunter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: curl -X POST -H 'Content-type: application/json' --data '{"text":"RECON LARGE SCOPE PRIVATE STARTED FOR DOMAIN - $TARGET"}' "$SLACK_WEBHOOK"
                
                       
