name: Dev-3
on:
  workflow_dispatch:
env:
       CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
       CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}
       S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       S_CHANNEL: ${{ secrets.DOMAIN_MONITORING_FOR_SUBS }}
       S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PRIVATE }}
       S_URL: https://slack.com/api/files.upload
jobs:
  Dev-3:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
      - name: DNSx
        run: |
         echo "dingo.example.com" > Domain_Monitoring/found_subdomains.txt
         cd Domain_Monitoring
         touch new_subdomains.txt
         python3 domain_monitoring.py
         sort -u new_subdomains.txt -o new_subdomains.txt
         cat new_subdomains.txt >> old_subdomains.txt
         sort -u old_subdomains.txt -o old_subdomains.txt
         cd ..
      - name: Output to Slack
        run: |
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=Private-BBP -F file=@Domain_Monitoring/new_subdomains.txt;
      - name: Commit resolvers.txt
        run: |
          cd Domain_Monitoring
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add old_subdomains.txt
          git commit -m "Update old_subdomains.txt" -a
          git push
