name: Dev-2
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN_DNSSEARCH }}
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
       CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
       CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}
jobs:
  HTTPX:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget -q https://github.com/tillson/git-hound/releases/download/v1.3/git-hound_1.3_Linux_x86_64.tar.gz
         tar -xzvf git-hound_1.3_Linux_x86_64.tar.gz
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
      - name: git-hound
        run: |
         echo "$TARGET" | ./git-hound --config-file Domain_Monitoring/config/githound-config.yml --dig-files --dig-commits | tee -a git-hound-output.txt

