name: Dev-2
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.TARGET_GITHUB_ORG }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
       S_CHANNEL: ${{ secrets.SLACK_CN_SOLO }}
#       CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
#       CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}
jobs:
  HTTPX:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         go env -w GOPATH=~/Downloads;
         GO111MODULE=on go get github.com/zricethezav/gitleaks/v7
         cp ~/Downloads/bin/gitleaks .; 
         curl -s 'https://api.github.com/orgs/'"$TARGET"'/repos?per_page=100&page=1' | jq '.[]|.clone_url' | cut -d '"' -f2 > git_repo_url.txt
#         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
#         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
#         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
      - name: gitleaks
        run: |
         cat git_repo_url.txt
         for url in $(cat git_repo_url.txt); do gitleaks --repo-url=$url -v --report=gitleak-report.json; done
      - name: Send Output to Slack
        if: always()
        run: |
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Gitleaks -F file=@gitleak-report.json
         
