name: Dev-2
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN_DNSSEARCH }}
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
jobs:
  HTTPX:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
      - name: DNSx
        run: |
         echo hai > output.txt
      - name: Send Output to Slack
        if: always()
        run: |
         SLACK_CHANNEL_NAME=$(echo $TARGET | sed 's/\./_/g')
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-DNSx -F file=@output.txt

  HTTPX2:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
      - name: DNSx
        run: |
         echo hello > output.txt
      - name: Send Output to Slack
        if: always()
        run: | 
         SLACK_CHANNEL_NAME=$(echo $TARGET | sed 's/\./_/g')
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-DNSx -F file=@output.txt
