name: Dev-4
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      HOST: ${{ secrets.NGROK_URL }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}        
jobs:
  teemo-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Teemo
        run: |
          git clone https://github.com/bit4woo/teemo.git
          sudo apt install python2-pip
          pip2 install -r teemo/requirements.txt
          python2 teemo/teemo.py -h
