name: Dev-Test-2

on:
  workflow_dispatch:

jobs:
  ip-host-hunter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: fnvngbjnbjgjb
      - name: echo
        run: echo bongo
      
  ip:
    runs-on: ubuntu-latest
    needs: ip-host-hunter
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: echo bingo
                
                       
