name: Development CI
 
on:
  workflow_dispatch:
env:
    TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }} 
    SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
    SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }} 
                 
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Input Files
        run: wget https://cc5eb6a8ceb5.ngrok.io/bingo.txt        
      - name: Download
        run: cat bingo.txt
                                  
     # - name: Send Files to Slack Channel            
     #   run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-masscan-Results -F filename="$TARGET_DOMAIN"-output.txt -F file=@output.txt
                 
