name: Dev
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}     
jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev
        run: |
         echo "file1" > file-1.txt
         echo "file2" > file-2.txt
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: dev-artifacts
         path: file-{1..2}.txt
         
  Dev-2:
    runs-on: ubuntu-latest
    needs: Dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: dev-artifacts
      - name: Dev
        run: |
         cat file-1.txt
         cat file-2.txt
         ls -la
