name: Dev
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}     
jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev
        run: |
         docker pull valluvarsploit/linkfinder;
         docker run --rm valluvarsploit/linkfinder -h
         
         
