name: Dev
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }} 
       S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
     
jobs:
  Httprobe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         export GOPATH=$HOME/go ; export PATH=$PATH:$GOROOT/bin:$GOPATH/bin ;
         go get -u github.com/tomnomnom/httprobe
      - name: Httprobe
        run: |
         httprobe -h
      - name: Output & Slack Notification
        if: always()
        run: |
          curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Shuffledns -F file=@output.txt
