name: Dev
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}    
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_URL: https://slack.com/api/files.upload
jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev
        run: |
         git clone https://github.com/0xsha/GoLinkFinder.git

         cp ~/Downloads/bin/GoLinkFinder .
         GoLinkFinder -h
#         docker pull valluvarsploit/linkfinder;
#         docker run --rm valluvarsploit/linkfinder -d -i https://google.com -o cli >> js-endpoints.txt;
#        xz js-endpoints.txt;
#        S_CHANNEL=$(echo $TARGET | sed 's/\./_/g');
#        curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=Docker-Test -F file=@js-endpoints.txt.xz;
         
         
