#Stage 12
#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. TARGET_DOMAIN    , formtat below
#       example.com
#  2. TARGET_IP_LIST    , format below
#       1.1.1.1
#       2.2.2.2

#workflow Dependent on: subdomain_enumeration.yml
#file dependent on: masscan_to_nmap.py

name: Masscan
 
on:
  workflow_dispatch:

jobs:
  masscan:
    runs-on: ubuntu-latest
    env:
                 TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }} 
                 TARGET_IP_LIST: ${{ secrets.TARGET_IP_LIST }}
                 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}                 
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
                 sudo apt-get update && sudo apt-get install nmap -y
                 pip install python-libnmap
                 sudo apt-get install git gcc make libpcap-dev
                 git clone https://github.com/robertdavidgraham/masscan
                 cd masscan && make -j && cp bin/masscan ../masscanb
                 
      - name: Input Files
        run: |
                 echo "$TARGET_IP_LIST" > targets.txt
           
      - name: Masscan
        run: | 
                 sudo ./masscanb -iL targets.txt --rate 10000 -p1-65535 -oX masscan.xml
                 
      - name: Masscan to Nmap
        run: |
                 python masscan_to_nmap.py masscan.xml | tee -a nmap-masscan.txt
                 
      - name: Send File to Slack Channel            
        run: |           
                 curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Masscan-Results -F filename="$TARGET_DOMAIN"-masscan.xml -F file=@masscan.xml
                 curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Nmap-Masscan-Results -F filename="$TARGET_DOMAIN"-nmap-masscan.txt -F file=@nmap-masscan.txt
                 
