name: Dev-Test
on:
  workflow_dispatch:
env:
       TARGET_DOMAIN: ${{ secrets.TARGET_GITHUB_DOMAIN }}
       TARGET_USERS_FILE: ${{ secrets.TARGET_GITHUB_USERS_LIST }}
       TARGET_ORG: ${{ secrets.TARGET_GITHUB_ORG }}
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }} 
jobs:
