name: Dev-Test
on:
  workflow_dispatch:
env:
   TARGET: ${{ secrets.PUBLIC_DOMAIN }}
   HOST: https://33f66254def1.ngrok.io
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.PUBLIC_SLACK_CHANNEL_NAME }}

jobs:  
  cloud-enum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         echo "bingo" > subdomains.txt
         echo "jingo" > cloud-enum.log
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: subdomain-enumeration-artifacts
         path: |
           subdomains.txt 
           cloud-enum.log
           
  cloud-enum2:
    runs-on: ubuntu-latest
    needs: [cloud-enum]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: subdomain-enumeration-artifacts
      - name: Install Dependencies
        run: |
           cat subdomains.txt 
           cat cloud-enum.log
