name: ShuffleDNS
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }} 
       S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
jobs:
  ShuffleDNS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo cp binaries/massdns /usr/bin/massdns
         sudo chmod +x /usr/bin/massdns
         chmod +x binaries/shuffledns ;
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt ;
         cd wordlists ;
         xz -d subdomains-w{1..2}.txt.xz subdomains-1m-{1..13}.txt.xz ;
         cat subdomains-w{1..2}.txt commonspeak2-subdomains.txt bitquark-subdomains-top100000.txt subdomains-1m-{1..13}.txt > ../subdomain-wordlists.txt ;
         cd .. ;
      - name: ShuffleDNS
        run: |
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlist-hugh.txt ;
         cat wordlist-hugh.txt > target.txt
         ls -l
         ./binaries/shuffledns -d "$TARGET" -list target.txt -r resolvers.txt
      - name: Output & Slack Notification
        if: always()
        run: |
          curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Shuffledns -F file=@wordlist-hugh-head.txt
