name: Dev-Test
on:
  workflow_dispatch:
env:
   TARGET: ${{ secrets.PUBLIC_DOMAIN }}
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.PUBLIC_SLACK_CHANNEL_NAME }}

jobs:  
  parameter-discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         echo "$TARGET"
         cd binaries; chmod +x shuffledns; cd ..
         git clone https://github.com/blechschmidt/massdns.git ; cd massdns/ ; make ; sudo mv bin/massdns /usr/bin/massdns; cd .. ;
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt
         sed "s/$/.$TARGET/" wordlists/subdomain-wordlists.txt > wordlist-hugh.txt
      - name: ShuffleDNS
        run: ./binaries/shuffledns -d $TARGET --list wordlist-hugh.txt -r resolvers.txt -v -o shuffledns.txt 

