name: Dev-Test
on:
  workflow_dispatch:
env:
   TARGET: ${{ secrets.PUBLIC_DOMAIN }}
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.PUBLIC_SLACK_CHANNEL_NAME }}

jobs:  
  parameter-discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt
         sed "s/$/.$TARGET/" wordlists/subdomain-wordlists.txt > wordlist-hugh.txt
       #git clone https://github.com/blechschmidt/massdns.git ; cd massdns/ ; make ; cd .. ;
       #cd binaries; chmod +x shuffledns; cd ..
       #git clone https://github.com/blechschmidt/massdns.git ; cd massdns/ ; make ; sudo mv bin/massdns /usr/bin/massdns; cd .. ;
      - name: ShuffleDNS
        run: |
         ./massdns/bin/massdns -r resolvers.txt -t A -o S -w massdns-output.txt wordlist-hugh.txt
         #./binaries/shuffledns -d $TARGET --list wordlist-hugh.txt -r resolvers.txt -v -o shuffledns.txt 
         cat massdns-output.txt | awk '{print $1}' | sed 's/.$//' | sort -u > live-hosts-temp-output.txt
      - name: Send Output to Slack
        run: |
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=MassDNS-Live-IPs -F filename=live-hosts-temp-output.txt -F file=@live-hosts-temp-output.txt

