name: Dev-Test
on:
  workflow_dispatch:
env:
   HOST: ${{ secrets.NGROK_URL }}
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}

jobs:  
  nmap-udp-scan:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/subdomains.txt 
         wget $HOST/exclude.txt
         grep -vFf exclude.txt subdomains.txt > uniq.txt
         cat uniq.txt
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Test -F filename=uniq.txt -F file=@uniq.txt
#         sudo apt-get update && sudo apt-get install nmap -y
#      - name: Nmap UDP scan
#        run: sudo nmap -Pn -sV -sU -p- -iL targets-ips.txt -oA nmap-udp-scan
#      - name: Send Output to Slack
#        run: |
#         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Nmap-UDP-Scan -F filename=nmap-udp-scan.xml -F file=@nmap-udp-scan.xml
#         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Nmap-UDP-Scan -F filename=nmap-udp-scan.nmap -F file=@nmap-udp-scan.nmap
