name: Dev-Test
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }} 
jobs:
  DNSsearch-1:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         go env -w GOPATH=~/Downloads
         go get github.com/evilsocket/dnssearch
         cp ~/Downloads/bin/dnssearch .
         cd wordlists
         xz -d subdomains-1m-1.txt.xz; cd .. ;
      - name: DNSsearch
        run: ./dnssearch -domain "$TARGET" -wordlist wordlists/subdomains-1m-1.txt | tee dnssearch.txt ;
      - name: Send Output to Slack
        if: always()
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-DNSsearch -F filename=dnssearch.txt -F file=@dnssearch.txt

