name: Dev-Test
on:
  workflow_dispatch:
env:
      HOST: ${{ secrets.NGROK_URL }}

jobs:
  xsstrike:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/paramspider.txt
         git clone https://github.com/s0md3v/XSStrike.git
         pip3 install -r XSStrike/requirements.txt
      - name: GoChopChop
        run: for url in $(cat paramspider.txt); do echo "checking $url"; python3 ~/Desktop/bugBounty/tools/XSStrike/xsstrike.py --url $url; echo Completed- $url ; done;

