name: Dev-Test
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.PUBLIC_DOMAIN }}
      EXCLUDE_HOST: ${{ secrets.PUBLIC_EXCLUDE_HOST }}
      HOST: ${{ secrets.NGROK_URL }}
      AWS_CREDS: ${{ secrets.AWS_CREDENTIALS }}
      XSS_HUNTER_URL_TOKEN: ${{ secrets.XSS_HUNTER_BLIND_URL_TOKEN }}
      SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      SLACK_CHANNEL_NAME: ${{ secrets.PUBLIC_SLACK_CHANNEL_NAME }}

jobs:
  xsstrike:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget HOST/paramspider.txt
         git clone https://github.com/s0md3v/XSStrike.git
         pip3 install -r XSStrike/requirements.txt
      - name: GoChopChop
        run: for url in $(cat paramspider.txt); do echo "checking $url"; python3 ~/Desktop/bugBounty/tools/XSStrike/xsstrike.py --url $url; echo Completed- $url ; done;

