name: Dev-Test-3
on:
  workflow_dispatch:
env:
       TARGET: stripe.com
       TARGET_GIT_REPO_URLS: ${{ secrets.GIT_REPO_URLS }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }} 
jobs:
  gf-patterns:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: bignobbgb
      - name: Send Output to Slack
        if: job.failure
        run: echo bingo
