name: Dev-Test
on:
  workflow_dispatch:
env:
      ALIENT_VALUT: ${{ secrets.AMASS_ALIENVALUT }}
      CLOUDFLARE: ${{ secrets.AMASS_CLOUDFLARE }}
      FACEBOOK: ${{ secrets.AMASS_FACEBOOK }}
      NETWORKSDB: ${{ secrets.AMASS_NETWORKSDB }}
      RECONDEV: ${{ secrets.AMASS_RECONDEV }}
      WHOISXMLAPI: ${{ secrets.AMASS_WHOISXMLAPI }}

jobs:
  xsstrike:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         
         git clone https://github.com/s0md3v/XSStrike.git
         pip3 install -r XSStrike/requirements.txt
      - name: XSStrike
        run: for url in $(cat paramspider.txt); do echo "checking $url"; python3 XSStrike/xsstrike.py --url $url; echo Completed- $url ; done;

