name: Dev-Test
on:
  workflow_dispatch:
env:
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_PRIVATE }} 
jobs:
  DNSsearch:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         go env -w GOPATH=~/Downloads
         go get github.com/evilsocket/dnssearch
         cp ~/Downloads/bin/dnssearch .
         ./dnssearch
       #cd dnssearch
       #go build -o dnssearch main.go
         
#      - name: Send Output to Slack
#        if: always()
#        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Nmap-Vulnerability-Scan -F filename=nmap-vulnerability-scan.txt  -F file=@nmap-vulnerability-scan.txt
