name: Slack Channel Creation
on:
  workflow_dispatch:
env:
   TARGETS: google.com
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}

jobs:  
  nikto-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dev
      - run : |
         sudo npm install broken-link-checker -g 
         blc --help
     #curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Nikto -F filename="$TARGET"-nikto-output.txt -F file=@nikto-output.txt
    


