name: ShuffleDNS
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }} 
       S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
jobs:
  ShuffleDNS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo cp binaries/massdns /usr/bin/massdns
         chmod +x binaries/shuffledns ;
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt ;
      - name: ShuffleDNS
        run: |
         sed "s/$/.$TARGET/" wordlists/commonspeak2-subdomains.txt > wordlist-hugh.txt ;
         cat wordlist-hugh.txt | head > wordlist-hugh-head.txt
         ./binaries/shuffledns -d "$TARGET" -list wordlist-hugh.txt -r resolvers.txt -o output.txt
         ls -l
      - name: Output & Slack Notification
        if: always()
        run: |
          curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Shuffledns -F file=@wordlist-hugh-head.txt
