name: Dev-Test
on:
  workflow_dispatch:
env:
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.PUBLIC_SLACK_CHANNEL_NAME }}

jobs:  
  parameter-discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         cd binaries; chmod +x shuffledns; cd ..
         git clone https://github.com/blechschmidt/massdns.git ; cd massdns/ ; make ; sudo mv bin/massdns /usr/bin/massdns       
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt
      - name: ShuffleDNS
        run: ./binaries/shuffledns -d "$TARGET" -w wordlists/subdomain-wordlists.txt -r resolvers.txt -v -o shuffledns-brute.txt 

