name: Dirsearch Files
on:
  workflow_dispatch:
env:
      HOST: ${{ secrets.NGROK_URL }}
      SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      SLACK_CHANNEL_NAME: ${{ secrets.PUBLIC_SLACK_CHANNEL_NAME }}
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}
jobs:
  dirsearch-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Install Dependencies
        run: |
         wget $HOST/subdomains-live.txt 
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
         bash Domain_Monitoring/scripts/dirsearch-file.sh subdomains-live.txt
      - name: Send Outputs to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Dirsearch -F filename=dirsearch-reports.zip.xz -F file=@dirsearch-file-reports.zip.xz
