name: Dirsearch
on:
  workflow_dispatch:
env:
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
jobs:
 dirsearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/http-resolved-url.txt -O target.txt
         git clone https://github.com/maurosoria/dirsearch.git
         python3 dirsearch/dirsearch.py -h
