name: Dirsearch
on:
  workflow_dispatch:
env:
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
jobs:
 dirsearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/http-resolved-url.txt -O target.txt
         wget https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-large-files.txt
         git clone https://github.com/maurosoria/dirsearch.git
      - name: Dirsearch
        run: |
         python3 dirsearch/dirsearch.py -l target.txt -e .* -w raft-large-files.txt --simple-report=dirsearch.out -t 50
         zip -r reports-all.zip dirsearch/reports && xz reports-all.zip
      - name: Send Output to Slack
        run: |
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Dirsearch-Report -F filename=dirsearch.out -F file=@dirsearch.out
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Dirsearch-Report-All -F filename=reports-all.zip.xz -F file=@reports-all.zip.xz
