name: Docker
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_URL: https://slack.com/api/files.upload      
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker
        run: |
         git clone https://github.com/ValluvarSploit/SubDomainizer.git; cd SubDomainizer;
         docker build -t valluvarsploit/subdomainizer .;
         docker run --rm -v `pwd`:/subdomainizer valluvarsploit/subdomainizer -u https://www.grindr.com -o /subdomainizer/subdomainizer.txt;
         cat subdomainizer.txt | wc -l;
#         echo "$DOCKER_PASSWORD" | docker login --username=valluvarsploit --password-stdin;
#         docker push valluvarsploit/subdomainizer;
      - name: Slack
        run: |
         ls -la
         pwd
         S_CHANNEL=$(echo $TARGET | sed 's/\./_/g');
         curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=Subdomainizer -F file=@SubDomainizer/subdomainizer.txt;
