name: Docker Image Creation
on:
  workflow_dispatch:
env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Docker-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Eyewitness Screenshot
        run: |
         git clone https://github.com/ValluvarSploit/subscraper.git; cd subscraper;
         docker build -t valluvarsploit/subscraper .;
         docker run --rm -v `pwd`:/tmp valluvarsploit/subscraper example.pl -o /tmp/subs.subscrap;
         echo "$DOCKER_PASSWORD" | docker login --username=valluvarsploit --password-stdin;
         docker push valluvarsploit/subscraper
         docker pull valluvarsploit/subscraper:latest;
