name: Docker
on:
  workflow_dispatch:
env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker
        run: |
         git clone https://github.com/GerbenJavado/LinkFinder.git; cd LinkFinder;
         docker build -t valluvarsploit/linkfinder .;
         docker run --rm -v `pwd`:/linkfinder/output valluvarsploit/linkfinder -i http://example.com/1.js -o /linkfinder/output/output.html;
         echo "$DOCKER_PASSWORD" | docker login --username=valluvarsploit --password-stdin;
         docker push valluvarsploit/subscraper;
#         docker run --rm -v `pwd`:/tmp valluvarsploit/subscraper example.pl -o /tmp/subs.subscrap;
#         echo "$DOCKER_PASSWORD" | docker login --username=valluvarsploit --password-stdin;
#         docker push valluvarsploit/subscraper
#         docker pull valluvarsploit/subscraper:latest;
#         wget https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt;
