name: Docker
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_URL: https://slack.com/api/files.upload      
jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker
        run: |
         git clone https://github.com/ValluvarSploit/SubDomainizer.git; cd SubDomainizer;
         docker build -t valluvarsploit/subdomainizer .;
         docker run --rm -v `pwd`:/subdomainizer valluvarsploit/subdomainizer -u https://www.grindr.com -o subdomainizer/subdomainizer.txt;
         cat subdomainizer.txt | head;
#         echo "$DOCKER_PASSWORD" | docker login --username=valluvarsploit --password-stdin;
#         docker push valluvarsploit/subdomainizer;
         
#         docker run --rm valluvarsploit/golinkfinder -h;
#         docker run --rm -v `pwd`:/golinkfinder/ valluvarsploit/golinkfinder -d allegro.pl -o /golinkfinder/golinkfinder-js-end-urls.txt;
#         
#         docker push valluvarsploit/golinkfinder;
#         docker run --rm -v `pwd`:/linkfinder/output valluvarsploit/linkfinder -i https://allegro.pl -o /linkfinder/output/output.html;
#         echo "$DOCKER_PASSWORD" | docker login --username=valluvarsploit --password-stdin;
#         docker push valluvarsploit/linkfinder;
#         docker run --rm -v `pwd`:/tmp valluvarsploit/subscraper example.pl -o /tmp/subs.subscrap;
#         echo "$DOCKER_PASSWORD" | docker login --username=valluvarsploit --password-stdin;
#         docker push valluvarsploit/subscraper
#         docker pull valluvarsploit/subscraper:latest;
#         wget https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt;
