name: Download Binaries
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         token: ${{ secrets.TOKEN }} 
      - name: Download binaries
        run: |         
         git clone https://github.com/blechschmidt/massdns.git ; cd massdns/ ; make ; cd ..; mv massdns/bin/massdns binaries/massdns
         
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add binaries/
          git commit -m "binaries" -a
          git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/BBP-Private.git" HEAD:main --follow-tags

