name: File Downloader

on:
  workflow_dispatch:
  
jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         token: ${{ secrets.TOKEN }} 
         
      - name: Downloader
        run: |
          wget --quiet https://s3.amazonaws.com/assetnote-wordlists/data/automated/httparchive_directories_1m_2020_11_18.txt
          mv httparchive_directories_1m_2020_11_18.txt wordlists/directories.txt
      - name: Commit Downloaded Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Downloaded" -a
          git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/BBP-Private.git" HEAD:main --follow-tags

