#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. DOMAIN 
#       example.com
#  2. DOMAIN_SUBDOMAINS_HTTPS
#       https://example.com
#       https://info.example.com

name: Eyewitness-Web Screenshot
on:
  workflow_dispatch:
env:
       TARGET_DOMAIN: ${{ secrets.DOMAIN }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_PRIVATE_BB_CHANNEL_NAME }}
jobs:
 eyewitness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget https://e1b9fbc091de.ngrok.io/http-resolved-url.txt
         git clone https://github.com/FortyNorthSecurity/EyeWitness.git && cd EyeWitness/Python/setup && sudo ./setup.sh     
      - name: Eyewitness
        run: |
         python3 EyeWitness/Python/EyeWitness.py --web -f http-resolved-url.txt --timeout 60 --no-prompt
         mv `date +"%Y"`* eyewitness_output
         zip -r eyewitness_output.zip eyewitness_output && xz eyewitness_output.zip
      - name: Send Output Files Slack Channel
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Web-Screenshots -F filename="$TARGET_DOMAIN"-web-screens.zip.xz -F file=@eyewitness_output.zip.xz
                 
