name: GCPBucketBrute
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      HOST: ${{ secrets.NGROK_URL }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}        
jobs:
  cors-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CORS Scanner
        run: |
          git clone https://github.com/RhinoSecurityLabs/GCPBucketBrute.git;
          cd GCPBucketBrute/;
          pip3 install -r requirements.txt;
          python3 gcpbucketbrute.py -k allegro.pl -o gcp-buckets.txt --unauthenticated;
      - name: Output & Slack Notification
        if: always()
        run: |
          S_CHANNEL=$(echo $TARGET | sed 's/\./_/g');
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=Google-Cloud-Bucket -F file=@gcp-buckets.txt;
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job *${{ github.job}}* in workflow *${{ github.workflow }}* has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK";
