name: Git Enumeration

on:
  workflow_dispatch:

jobs:
  git-enumeration:
    runs-on: ubuntu-latest
    env:
                GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
                wget --quiet https://github.com/tillson/git-hound/releases/download/v1.3/git-hound_1.3_Linux_x86_64.tar.gz
                tar xvf git-hound_1.3_Linux_x86_64.tar.gz
                
      - name: Remove Exisiting Output Files
        run: |
        # rm git-hound-output.txt
                #echo -e "github_username: "$GIT_USERNAME"\ngithub_password: "$GIT_PASSWORD"" > config.yml
      - name: git-hound
        run: |
                echo "github_username: "$GIT_USERNAME"" > config.yml
                echo "github_password: "$GIT_PASSWORD"" >> config.yml
                ./git-hound --subdomain-file live-httpx-subdomains-hosts-output.txt --dig-files --dig-commits --config-file config.yml >> git-hound-output.txt
            
      - name: Display Output Files
        run: |
                echo "git-hound-output.txt"
                cat git-hound-output.txt
                
      - name: Remove Installation Files  
        run: |
                rm LICENSE README.md git-hound git-hound_1.3_Linux_x86_64.tar.gz config.yml
                             
      - name: Commit Tool Output
        run: |
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"
                git add git-hound-output.txt
                git commit -m "git enumeration"
                git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags 
