name: Git Enumeration

on:
  workflow_dispatch:

jobs:
  git-enumeration:
    runs-on: ubuntu-latest
    env:
                GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
                TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
                TARGET_USERS_FILE: ${{ secrets.TARGET_GITHUB_USERS_LIST }}
                TARGET_ORG: ${{ secrets.TARGET_GITHUB_ORG }}
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
                 git clone https://github.com/obheda12/GitDorker.git
                 pip3 install -r GitDorker/requirements.txt
                
      - name: Input Files
        run: |
                 echo "$TARGET_USERS_FILE" > git-users.txt
                           
      - name: Git-Dorker
        run: |
                 python3 GitDorker/GitDorker.py --dorks test.txt --userfile git-users.txt --organization "$TARGET_ORG" --token "$GITHUB_TOKEN" -o git-output.txt
     # python3 GitDorker/GitDorker.py --dorks GitDorker/Dorks/alldorksv2 --userfile git-users.txt --organization "$TARGET_ORG" --token "$GITHUB_TOKEN" -o git-output.txt
                
      - name: Send Output Files Slack Channel
        run: |
                 curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Gitdorker-Results -F filename="$TARGET_DOMAIN"-gitdorker.txt -F file=@git-output.txt
