name: Git Dorker
on:
  workflow_dispatch:
jobs:
  git-dorker:
    runs-on: ubuntu-latest
    env:
       TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
       TARGET_USERS_FILE: ${{ secrets.TARGET_GITHUB_USERS_LIST }}
       TARGET_ORG: ${{ secrets.TARGET_GITHUB_ORG }}
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}                
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo apt-get install python3-setuptools
         git clone https://github.com/obheda12/GitDorker.git
         pip3 install -r GitDorker/requirements.txt 
       #echo "$TARGET_USERS_FILE" > git-users.txt
      - name: Git-Dorker
        run: |
         python3 GitDorker/GitDorker.py --dorks GitDorker/Dorks/alldorksv2 --organization "$TARGET_ORG" --token "$GITHUB_TOKEN" -o git-output.txt
        #  python3 GitDorker/GitDorker.py --dorks test.txt --userfile git-users.txt --token "$GITHUB_TOKEN" -o git-output.txt
        #python3 GitDorker/GitDorker.py --dorks GitDorker/Dorks/alldorksv2 -q "$TARGET_DOMAIN"  --token "$GITHUB_TOKEN" -o git-output.txt       
      - name: Send Output Files Slack Channel
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Gitdorker-Results -F filename=gitdorker.csv -F file=@git-output.txt_gh_dorks.csv
                 
