name: Git Enumeration

on:
  workflow_dispatch:

jobs:
  git-enumeration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
                wget --quiet https://github.com/tillson/git-hound/releases/download/v1.3/git-hound_1.3_Linux_x86_64.tar.gz
                tar xvf git-hound_1.3_Linux_x86_64.tar.gz
                
      - name: Remove Exisiting Output Files
        run: |
        # rm git-hound-output.txt
                
      - name: git-hound
        run: |
                ./git-hound --subdomain-file live-httpx-subdomains-hosts-output.txt --results-only --dig-files --dig-commits --config-file config.yml |  tee -a git-hound-output.txt
            
      - name: Display Output Files
        run: |
                echo "git-hound-output.txt"
                cat git-hound-output.txt
                
      - name: Remove Installation Files  
        run: |
                rm LICENSE README.md git-hound git-hound_1.3_Linux_x86_64.tar.gz
                             
      - name: Commit Tool Output
        run: |
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"
                git add git-hound-output.txt
                git commit -m "git enumeration results"
                git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags 
