name: Gobuster Files Brute
on:
  workflow_dispatch:
env:
       URL: ${{ secrets.URL_GOBUSTER }}
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
     
jobs:
  Gobuster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget https://github.com/OJ/gobuster/releases/download/v3.1.0/gobuster-linux-amd64.7z
         7z e gobuster-linux-amd64.7z ; chmod +x gobuster  
         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-large-files.txt -O wordlist.txt
#         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-large-directories.txt -O wordlist.txt      
#       cp wordlists/sensitive-wordlist.txt wordlist.txt
#wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/common.txt -O wordlist.txt
#         
#         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-large-files.txt -O wordlist.txt
#         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-small-directories.txt -O wordlist.txt
      - name: Gobuster
        run: |
         ./gobuster dir -u "$URL" -w wordlist.txt -o gobuster.txt -a Mozilla/5.0 -e
      - name: Slack Output
        if: always()
        run: |
         S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-GoBuster -F file=@gobuster.txt
