name: Gobuster Files Brute
on:
  workflow_dispatch:
env:
       URL: ${{ secrets.URL_GOBUSTER }}
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
     
jobs:
  Gobuster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget https://github.com/OJ/gobuster/releases/download/v3.1.0/gobuster-linux-amd64.7z
         7z e gobuster-linux-amd64.7z ; chmod +x gobuster         
         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-large-directories.txt -O wordlist.txt      
#       cp wordlists/sensitive-wordlist.txt wordlist.txt
#wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/common.txt -O wordlist.txt
#         
#         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-large-files.txt -O wordlist.txt
#         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-small-directories.txt -O wordlist.txt
      - name: Gobuster
        run: |
         ./gobuster dir -u "$URL" -w wordlist.txt -o gobuster.txt -a Mozilla/5.0 -e -k --wildcard
      - name: Slack Output
        if: always()
        run: |
         S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-GoBuster -F file=@gobuster.txt


#  Gobuster-Files:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Dependencies
#        run: |
#         wget https://github.com/OJ/gobuster/releases/download/v3.1.0/gobuster-linux-amd64.7z
#         7z e gobuster-linux-amd64.7z ; chmod +x gobuster
#         wget -q https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-large-files.txt
#      - name: Gobuster
#        run: |
#         ./gobuster dir -u https://www.countertrade.com -w raft-large-files.txt -o gobuster-files.txt -a Mozilla/5.0
#         ./gobuster dir -u https://www.countertrade.com -w wordlists/sensitive-wordlist.txt -o gobuster-files.txt -a Mozilla/5.0
#      - name: Slack Output
#        if: always()
#        run: |
#         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=GoBuster-File-Brute-Single -F file=@gobuster-files.txt

  #  Gobuster-Files-Brute:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - name: Install Dependencies
  #        run: |
  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Gobuster Files Brute INITIATED FOR - '$TARGET'"}' "$WEBHOOK"
  #         wget $HOST/subdomains-resolved.txt
  #         wget --quiet https://wordlists-cdn.assetnote.io/data/kiterunner/swagger-wordlist.txt
  #         wget https://github.com/OJ/gobuster/releases/download/v3.1.0/gobuster-linux-amd64.7z
  #         7z e gobuster-linux-amd64.7z ; chmod +x gobuster
  #         mkdir gobuster-files-brute
  #      - name: Gobuster
  #        run: |
  #         for url in $(cat subdomains-resolved.txt) ; do ./gobuster dir -u $url -w swagger-wordlist.txt -o gobuster-files-brute/$(date '+%F%T.%N')-output.txt -a Mozilla/5.0 -e --wildcard ; done ;
  #         zip gobuster-files-brute.zip gobuster-files-brute
  #       #for url in $(cat subdomains-resolved.txt) ; do ./gobuster dir -u $url -w wordlists/sensitive-wordlist.txt -l -o gobuster-files-brute/$(date '+%F%T.%N')-output.txt -a Mozilla/5.0 -e --wildcard ; done ;
  #      - name: Output & Slack Notification
  #        if: always()
  #        run: |
  #         curl -X POST -H 'Content-type: application/json' --data '{"text":"Gobuster File Brute COMPLETED FOR - '$TARGET'"}' "$WEBHOOK"
  #         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-GoBuster-File-Brute -F file=@gobuster-files-brute
  
