name: HTTProber
on:
  workflow_dispatch:
env:
     HOST: ${{ secrets.NGROK_URL }}
     SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}

jobs:
  httprober:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2             
      - name: Install Dependencies
        run: |
         wget $HOST/http-resolved-url.txt -O targets.txt
         sudo chmod +x binaries/httprobe
      - name: HTTP Resolver
        run: cat targets.txt | ./binaries/httprobe | tee httprobe-resolved.txt
      - name: Send Output to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=HTTProber -F filename=httprobe-resolved.txt -F file=@httprobe-resolved.txt
