#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. TARGET_DOMAIN
#       example.com
#  2. NGROK_URL
#       https://ngrok.io

name: HTTProber
on:
  workflow_dispatch:
env:
     TARGET_DOMAIN: ${{ secrets.DOMAIN }} 
     TARGETS: ${{ secrets.NGROK_URL }}
     SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     SLACK_CHANNEL_NAME: ${{ secrets.SLACK_PRIVATE_BB_CHANNEL_NAME }}

jobs:
  httpx-resolver-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2             
      - name: Install Dependencies
        run: |
         wget $TARGETS/http-resolved-url.txt -O targets.txt
         wget $TARGETS/httprobe && sudo chmod +x httprobe
      - name: HTTPx Resolver
        run: cat targets.txt | ./httprobe | tee httprobe-resolved.txt
      - name: Send MassDNS Output Files to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-httprobe-resolved -F filename="$TARGET_DOMAIN"-httprobe-resolved.txt -F file=@httprobe-resolved.txt
