name: Javascript Monitor
on:
  workflow_dispatch:
env:
      CONFIG: ${{ secrets.NOTIFY_CONFIG }}
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }}        
jobs:
  javascript-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         mkdir ~/.config/notify; echo "$CONFIG" > ~/.config/notify/notify.conf;
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
         bash Domain_Monitoring/scripts/js-monitor.sh ""
         for domain in $(cat Domain_Monitoring/subdomain-monitoring/monitored_domains.txt); do bash Domain_Monitoring/scripts/js-monitor.sh -d "$domain" -l Domain_Monitoring/subdomain-monitoring/output/resolved/"$domain".txt ; done;
      - name: Commit Output
        run: |
         cd Domain_Monitoring/js-monitoring/output/
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add .
         git commit -m "Update JS links" -a
         git push
