name: MassDNS Resolver
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }} 
       WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}

jobs:
  massdns-resolver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2             
      - name: Install Dependencies
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"DNSsearch Bruteforce HAS STARTED FOR - '$TARGET'"}' "$WEBHOOK"
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt
         wget --quiet https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt
         git clone https://github.com/blechschmidt/massdns.git && cd massdns/ && make
      - name: MassDNS
        run: |
         sed "s/$/.$TARGET/" best-dns-wordlist.txt > wordlist-hugh.txt
         cat wordlist-hugh.txt | head
         ./massdns/bin/massdns -r resolvers.txt -t A -o S -w massdns-output.txt wordlist-hugh.txt
         cat massdns-output.txt | awk '{print $1}' | sed 's/.$//' | tr A-Z a-z | sort -u > live-hosts-output.txt
         cat massdns-output.txt | awk '{print $3}' | sort -u  > live-ips-output.txt         
      - name: Send Output to Slack
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"MassDNS Resolver COMPLETED FOR - '$TARGET'"}' "$WEBHOOK"
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-MassDNS-Live-IPs -F file=@live-ips-output.txt  
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-MassDNS -F file=@massdns-output.txt
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-MassDNS-Live-Hosts -F file=@live-hosts-output.txt
         
