  Mass-Nmap-Scan:
    if: always()
    runs-on: ubuntu-latest    
    needs: [Nuclei-Template-Scan, HTTProber]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: subdomains-artifacts
      - name: Masscan-Nmap 
        run: |
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
         bash Domain_Monitoring/scripts/masscan-nmap.sh ips-live.txt      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: nmap-output
         path: nmap-masscan.out         
      - name: Output & Slack Notification
        if: always()
        run: |
          S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$S_WEBHOOK" ;
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Mass-Nmap-Scan -F file=@mass-nmap-scan.zip
