name: Nikto Scan
on:
  workflow_dispatch:
env:
   TARGET: stripe.com
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}

jobs:  
  nikto-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo apt-get update && sudo apt-get install nikto -y
         echo "$TARGET" > targets.txt
      - name: Nikto Scan
        run: |
         for host in $(cat targets.txt) ; do nikto -h $host >> nikto-80-output.txt
         nikto -h $host:443 >> nikto-443-output.txt
         cat nikto-80-output.txt
         cat nikto-443-output.txt

