name: NMAP Full Scan
on:
  workflow_dispatch:
env:         
      TARGET: ${{ secrets.DOMAIN }}
      SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }}
      DOMAIN_IP_LIST: ${{ secrets.DOMAIN_IP_LIST }}
      WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
jobs:
  nmap-vulnerability-scan:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         echo "$DOMAIN_IP_LIST" > targets-ips.txt
         sudo apt-get update && sudo apt-get install nmap -y
         cd /usr/share/nmap/scripts/
         sudo git clone https://github.com/vulnersCom/nmap-vulners.git
         sudo git clone https://github.com/scipag/vulscan
         cd vulscan/utilities/updater/ ; sudo chmod +x updateFiles.sh ; sudo ./updateFiles.sh
      - name: Nmap scan
        run: |
         nmap -Pn -sV -p- --script nmap-vulners,vulscan,vuln --script-args vulscandb=scipvuldb.csv -iL targets-ips.txt -oN nmap-vulnerability-scan.txt 
         xz nmap-vulnerability-scan.txt
      - name: Send Output to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Nmap-Vulnerability-Scan -F filename=nmap-vulnerability-scan.txt.xz  -F file=@nmap-vulnerability-scan.txt.xz
      - name: Slack Notification
        if: always()
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"NMAP FULL SCAN COMPLETED FOR - '$TARGET'"}' "$WEBHOOK"          
          
  nmap-udp-scan:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         echo "$DOMAIN_IP_LIST" > targets-ips.txt
         sudo apt-get update && sudo apt-get install nmap -y
      - name: Nmap UDP scan
        run: sudo nmap -Pn -sV -p- -sU -iL targets-ips.txt -oA nmap-udp-scan
      - name: Send Output to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Nmap-UDP-Scan -F filename=nmap-udp-scan.nmap -F file=@nmap-udp-scan.nmap
      - name: Slack Notification
        if: always()
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"NMAP UDP SCAN COMPLETED FOR - '$TARGET'"}' "$WEBHOOK"          
