name: NMAP Full Scan
 
on:
  workflow_dispatch:

jobs:
  nmap-full-scan:
    runs-on: ubuntu-latest
    env:
                 TARGET_DOMAIN: ${{ secrets.DOMAIN }}
                 TARGET_IP: ${{ secrets.DOMAIN_IP_LIST }}
                 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_PRIVATE_BB_CHANNEL_NAME }}  
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
      
        run: sudo apt-get update && sudo apt-get install nmap -y

      - name: Input Files
        run: |
         echo "$TARGET_IP" > targets-ips.txt

      - name: Nmap scan
        run: nmap -Pn -sC -sV -iL targets-ips.txt -oA nmap-full-scan

      - name: Send Files to Slack Channel
        run: |
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Nmap-Full-Scan -F filename="$TARGET_DOMAIN"-nmap-scan.nmap -F file=@nmap-full-scan.nmap
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Nmap-Full-Scan -F filename="$TARGET_DOMAIN"-nmap-scan.xml -F file=@nmap-full-scan.xml

