name: NMAP 1000 Ports

on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       S_WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
       S_URL: https://slack.com/api/files.upload
       HOST: ${{ secrets.NGROK_URL}}
       CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
       CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }} 

jobs:
  nmap-1000-ports:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Nmap 1000 Ports scan
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The ${{ github.workflow }} has started for - '$TARGET'"}' "$S_WEBHOOK"
         wget -q $HOST/ips-live.txt
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git
         bash Domain_Monitoring/scripts/nmap-1000-scan.sh ips-live.txt  
      - name: Output & Slack Notification
        if: always()
        run: |
         S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
         curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Nmap-1000-Ports -F file=@nmap-1000-scan.zip
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_"}' "$S_WEBHOOK"
         
