name: Nuclei Scan Others templates CI
 
on:
  workflow_dispatch:

jobs:
  nuclei-others-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Clean-up
        run: |
         rm nuclie-others-output.txt
         touch nuclie-others-output.txt
      - name: Nuclei Others Scan
        run: |
         git clone https://github.com/projectdiscovery/nuclei-templates.git
         wget https://github.com/projectdiscovery/nuclei/releases/download/v2.2.0/nuclei_2.2.0_linux_amd64.tar.gz
         tar -xzvf nuclei_2.2.0_linux_amd64.tar.gz
         ./nuclei -l live-subdomains-output.txt -c 100 -stats -t nuclei-templates/ -exclude nuclei-templates/cves/ -exclude nuclei-templates/technologies/ -exclude nuclei-templates/default-credentials/ -exclude nuclei-templates/fuzzing/basic-auth-bruteforce.yaml -exclude nuclei-templates/fuzzing/wp-plugin-scan.yaml -exclude nuclei-templates/panels/ -exclude nuclei-templates/payloads/ -exclude nuclei-templates/security-misconfiguration/ -exclude nuclei-templates/wordlists/ -o nuclie-others-output.txt
         echo `date` | tee -a nuclie-others-output.txt
         rm LICENSE.md nuclei README.md nuclei_2.2.0_linux_amd64.tar.gz
         rm -rf nuclei-templates/
      - name: Commit Output file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add nuclie-others-output.txt
          git commit -m "Update nuclie-others-output.txt"
          git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags
