#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. DOMAIN
#       example.com
#  2. NGROK_URL
#       https://ngrok.io
name: Nuclei Scan
on:
  workflow_dispatch:
env:
     TARGET_DOMAIN: ${{ secrets.DOMAIN }} 
     HOST: ${{ secrets.NGROK_URL }}
     SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }}
jobs:
  nuclei-scan:
    runs-on: ubuntu-latest                 
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/httpx.out.xz ; xz -d httpx.out.xz
         git clone https://github.com/projectdiscovery/nuclei-templates.git
         wget --quiet https://github.com/projectdiscovery/nuclei/releases/download/v2.3.2/nuclei_2.3.2_linux_amd64.tar.gz
         tar -xzvf nuclei_2.3.2_linux_amd64.tar.gz
      - name: Nuclei scan
        run: |        
         ./nuclei -l httpx.out -c 500 -stats -t nuclei-templates/takeovers -o nuclie-scan.txt
         if [[ -f nuclie-scan.txt ]]; then curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Nuclei-Scan -F file=@nuclie-scan.txt; fi
                 
