name: Nuclei Scan
on:
  workflow_dispatch:
env:
     TARGET: ${{ secrets.DOMAIN }} 
     HOST: ${{ secrets.NGROK_URL }}
     S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     S_WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
     S_URL: https://slack.com/api/files.upload
jobs:
  nuclei-scan:
    runs-on: ubuntu-latest                 
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/subdomains-live.txt
         git clone https://github.com/projectdiscovery/nuclei-templates.git
         wget --quiet https://github.com/projectdiscovery/nuclei/releases/download/v2.3.2/nuclei_2.3.2_linux_amd64.tar.gz
         tar -xzvf nuclei_2.3.2_linux_amd64.tar.gz
      - name: Nuclei scan
        run: |        
         ./nuclei -l subdomains-live.txt -c 100 -stats -t nuclei-templates/ -o nuclie-scan.out ;
      - name: Output & Slack Notification
        if: always()
        run: |
          S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$S_WEBHOOK" ;
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Nuclei-Scan -F file=@nuclie-scan.out;

