name: ParamSpider
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       HOST: ${{ secrets.NGROK_URL }}
       S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       S_CHANNEL: ${{ secrets.SLACK_CN_SOLO }} 
       S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
       AWS_CREDS: ${{ secrets.AWS_CREDENTIALS }}
       S_URL: https://slack.com/api/files.upload
jobs:
  Parameter-Discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget https://475620573fa4.ngrok.io/subdomains-host.txt
         git clone https://github.com/devanshbatham/ParamSpider
         pip3 install -r ParamSpider/requirements.txt
         mkdir paramspider-out
      - name: ParamSpider
        run: |
         cat subdomains-host.txt | xargs -I % python3 ParamSpider/paramspider.py -l high --exclude woff,css,js,png,svg,php,jpg -o paramspider-out/% -d %;  
         cat paramspider-out/* > paramspider.txt ; sort -u paramspider.txt -o paramspider.txt;
         zip -r paramspider-out.zip paramspider-out/
      - name: Output & Slack Notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$S_WEBHOOK"
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-Parameter-Discovery -F file=@paramspider-out.zip
