name: RDP Pentesting
on:
  workflow_dispatch:
env:
   IP: ${{ secrets.TARGET_IP }}
   S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   S_CHANNEL: ${{ secrets.SLACK_CN_PRIVATE }}
   S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PRIVATE }}
   S_URL: https://slack.com/api/files.upload
   
jobs:
  #Bruteforce RDP username:password (Account may get locked)
  Hydra-RDP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Install Dependencies
        run: |
         sudo apt-get install hydra-gtk
         wget --quiet https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Default-Credentials/windows-betterdefaultpasslist.txt -O default.txt
      - name: Hydra-RDP
        run: |
         hydra -V -f -C default.txt rdp://"$IP" 
   
  #Checks for Encryption, DoS vuln (without causing DoS) and obtains NTLM Windows info (versions).    
  NMAP-RDP:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Install Dependencies
        run: |
         sudo apt-get update && sudo apt-get install nmap -y
      - name: NMAP-RDP-DoS Checker
        run: |
         nmap -Pn -sV --script "rdp-enum-encryption or rdp-vuln-ms12-020 or rdp-ntlm-info" -p 3389 -oN nmap-rdp.txt "$IP"
      - name: Output to Slack
        run:
         curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$IP"-NMAP-RDP -F file=@nmap-rdp.txt


