name: RDP Pentesting
on:
  workflow_dispatch:
env:
   IP: ${{ secrets.TARGET_IP }}
   
jobs:
#  Hydra-RDP:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2         
#      - name: Install Dependencies
#        run: |
#         sudo apt-get install hydra-gtk
#         wget --quiet https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Default-Credentials/windows-betterdefaultpasslist.txt -O default.txt
#      - name: Hydra-RDP
#        run: |
#         hydra -V -f -C default.txt rdp://"$IP" 
         
#  NMAP-RDP:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2         
#      - name: Install Dependencies
#        run: |
#         sudo apt-get update && sudo apt-get install nmap -y
#      - name: NMAP-RDP-DOS Checker
#        run: |
#         nmap -Pn -sV --script=rdp-vuln-ms12-020 -p 3389 "$IP" -v

  Impacket-RDP-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Install Dependencies
        run: |
         wget --quiet https://raw.githubusercontent.com/SecureAuthCorp/impacket/master/examples/rdp_check.py
         wget --quiet https://raw.githubusercontent.com/SecureAuthCorp/impacket/master/requirements.txt
         pip3 install -r requirements.txt
      - name: NMAP-RDP-DOS Checker
        run: |
         python3 rdp_check.py 96.65.26.181
