#Stage 10
#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. TARGET_DOMAIN    , formtat below
#       example

# Workflow Dependency: No

name: S3 Scanner

on:
  workflow_dispatch:

jobs:
  s3-bruteforce:
    runs-on: ubuntu-latest
    env:
                TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
                SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}                
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
                 git clone https://github.com/nahamsec/lazys3.git
                           
      - name: S3 Scanner
        run: |
                 cd lazys3/
                 ruby lazys3.rb "$TARGET_DOMAIN" | tee -a ../s3-bruteforece.txt

      - name: Send Output Files Slack Channel
        run: |
                 curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-S3-Bruteforce-Results -F filename="$TARGET_DOMAIN"-s3-bruteforce.txt -F file=@bruteforece.txt
                 
