name: S3Scanner
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      HOST: ${{ secrets.NGROK_URL }}
      AWS_CREDS: ${{ secrets.AWS_CREDENTIALS }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      S_WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
jobs:
  S3-Scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/subdomains-host.txt
         mkdir ~/.aws; echo "$AWS_CREDS" > ~/.aws/credentials
         pip3 install s3scanner
         for word in $(cat wordlists/bucket-wordist.txt); do echo $word.$TARGET >> targets-2.txt ; done; sort -u targets-2.txt -o targets-2.txt
         for word in $(cat wordlists/bucket-wordist.txt); do echo $word-$TARGET >> targets-3.txt ; done; sort -u targets-3.txt -o targets-3.txt
         touch buckets-{1..3}.txt
#         sudo apt-get install python3-setuptools
      - name: S3 Scanner
        run: |
         s3scanner scan --buckets-file subdomains-host.txt | grep -v "bucket_not_exist" | tee buckets-1.txt
         s3scanner scan --buckets-file targets-2.txt | grep -v "bucket_not_exist" | tee buckets-2.txt
         s3scanner scan --buckets-file targets-3.txt | grep -v "bucket_not_exist" | tee buckets-3.txt
         cat buckets-{1..3}.txt | sort -u > buckets.txt
      - name: Output & Slack Notification
        if: always()
        run: |
          S_CHANNEL=$(echo $TARGET | sed 's/\./_/g')
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$S_WEBHOOK"
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-S3-Scanner -F file=@buckets.txt
