name: Dirsearch Sensitive Files
on:
  workflow_dispatch:
env:
      HOST: ${{ secrets.NGROK_URL }}
      SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      SLACK_CHANNEL_NAME: ${{ secrets.PUBLIC_SLACK_CHANNEL_NAME }}
jobs:
  sensitive-files-fuzzing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Install Dependencies
        run: |
         wget $HOST/subdomains-live.txt 
         bash Domain_Monitoring/scripts/dirsearch-file.sh subdomains-live.txt
      - name: Send Outputs to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-Dirsearch -F filename=dirsearch-reports.zip.xz -F file=@dirsearch-file-reports.zip.xz
