 #Stage 9
#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. TARGET_DOMAIN 
#       https://example.com

name: Single Domain Pentest

on:
  workflow_dispatch:

env:
 TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}    
                
jobs:
  broken-link-hijacking:
    runs-on: ubuntu-latest            
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo npm install broken-link-checker -g                         
      - name: blh
        run: blc -rof --filter-level 3 https://$TARGET_DOMAIN | tee -a blh-output.txt
      - name: Send Output Files Slack Channel
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-blh-Results -F filename="$TARGET_DOMAIN"-blh.txt -F file=@blh-output.txt
                 
