name: Solo-Masscan Vs Nmap Scan
on:
  workflow_dispatch:
env:        
       HOST: ${{ secrets.NGROK_URL }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
       
jobs:
  masscan-nmap-scan:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         wget $HOST/live-ips.out -O targets.txt
         sudo apt-get update && sudo apt-get install nmap -y
         pip install python-libnmap
         sudo apt-get install git gcc make libpcap-dev
         git clone https://github.com/robertdavidgraham/masscan
         cd masscan && make -j && cp bin/masscan ../masscanb              
      - name: Masscan
        run: sudo ./masscanb -iL targets.txt --rate 10000 -p0-65535 -oX masscan.xml
      - name: Nmap Scan
        run: python masscan_to_nmap.py masscan.xml | tee -a nmap-masscan.txt      
      - name: Send Output to Slack             
        run: |           
          curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Masscan -F filename=masscan.xml -F file=@masscan.xml
          curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Nmap-Scan -F filename=nmap-scan.out -F file=@nmap-masscan.txt
                 
