name: URL Collector

on:
  workflow_dispatch:
env:
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_PRIVATE_BB_CHANNEL_NAME }}
jobs:
  url-collector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         go env -w GOPATH=~/Downloads
         go get -u github.com/tomnomnom/waybackurls
         go get -u github.com/tomnomnom/gf
         mkdir ~/.gf; cp -r ~/Downloads/src/github.com/tomnomnom/gf/examples ~/.gf
         git clone https://github.com/1ndianl33t/Gf-Patterns
         mv Gf-Patterns/*.json ~/.gf
         cp ~/Downloads/bin/gf . ; cp ~/Downloads/bin/waybackurls .
         chmod +x binaries/gau
      - name: waybackurls & gau
        run: |
         for url in $(cat subdomains-resolved-host.txt); do ./waybackurls "$url" >> waybackurls.txt; done;
         for url in $(cat subdomains-resolved-host.txt); do ./binaries/gau "$url" >> gau.txt; done;
         cat gau.txt | sort -u >> waybackurls.txt
      - name: Patterns
        run: |
         mkdir url-collector-artifacts
         cp waybackurls.txt url-collector-artifacts/
         cat waybackurls.txt | ./gf ssrf | sort -u > url-collector-artifacts/ssrf-params.txt
         cat waybackurls.txt | ./gf sqli | sort -u > url-collector-artifacts/sqli-params.txt
         cat waybackurls.txt | ./gf ssti | sort -u > url-collector-artifacts/ssti-params.txt
         cat waybackurls.txt | ./gf xss | sort -u > url-collector-artifacts/xss-params.txt
         cat waybackurls.txt | ./gf lfi | sort -u > url-collector-artifacts/lfi-params.txt
         cat waybackurls.txt | ./gf rce | sort -u > url-collector-artifacts/rce-params.txt
         cat waybackurls.txt | ./gf redirect | sort -u > url-collector-artifacts/redirect-params.txt
         cat waybackurls.txt | ./gf img-traversal | sort -u > url-collector-artifacts/img-traversal.txt
         zip -r url-collector-artifacts.zip url-collector-artifacts/ ; xz url-collector-artifacts.zip
      - name: Send Output to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-URL-Pattern-Collector -F filename=url-collector-artifacts.zip.xz -F file=@url-collector-artifacts.zip.xz
