name: Solo-Broken Link Checker
on:
  workflow_dispatch:
env:
   TARGET: hyperwallet.com
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}  
jobs:
  broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo npm install broken-link-checker -g                         
      - name: Broken Link Checker
        run: |
         echo "$TARGET" > targets.txt
         while read url ; do printf **"$url"** | tee -a blh-output.txt; blc -rof --filter-level 3 $url | tee -a blh-output.txt; done < targets.txt
      - name: Send Output Files Slack Channel
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Broken-Link-Checker -F filename=blc.out -F file=@blh-output.txt
