name: Aquatone-Webscreenshot
on:
  workflow_dispatch:
env:
   TARGET_DOMAIN: ${{ secrets.DOMAIN }}
   TARGETS: ${{ secrets.NGROK_URL }}
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.SLACK_PRIVATE_BB_CHANNEL_NAME }}

jobs:       
  aquatone-webscreenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         echo "https://google.com" > targets.txt
         go env -w GOPATH=~/Downloads;
         go get github.com/michenriksen/aquatone
         cp ~/Downloads/bin/aquatone .; 
      - name: Aquatone
        run: |
         mkdir aquatone-output
         cat targets.txt | ./aquatone -chrome-path /snap/bin/chromium -out aquatone-output/ -threads 50 -silent
         zip -r aquatone-output.zip aquatone-output/ && xz aquatone-output.zip
      - name: Send Output to Slack
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET_DOMAIN"-Aquatone-Webscreenshot -F filename="$TARGET_DOMAIN"-aquatone.zip.xz -F file=@aquatone-output.zip.xz
