name: Solo-Broken Link Checker
on:
  workflow_dispatch:
env:
   TARGET: ${{ secrets.DOMAIN }}
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
   HOST: ${{ secrets.NGROK_URL }}
jobs:
  broken-link-checker-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo npm install broken-link-checker -g    
         wget $HOST/subdomains-manual.txt
      - name: Broken Link Checker
        run: |
         for url in $(cat subdomains-manual.txt) ; do printf **"$url"** | tee -a blh-full.txt; blc -rof --filter-level 3 $url | tee -a blh-full.txt; done ;
      - name: Send Output Files Slack Channel
        run: |
         cat blh-full.txt | grep -v "├───OK───" > blh-full-broken.txt
         zip blc-full.zip blh-full.txt blh-full-broken.txt
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Broken-Link-Checker-Full -F file=@blc-full.zip

  broken-link-checker-light:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo npm install broken-link-checker -g    
         wget $HOST/subdomains-manual.txt
      - name: Broken Link Checker
        run: |
         for url in $(cat subdomains-manual.txt) ; do printf **"$url"** | tee -a blh-light.txt; blc -of --filter-level 0 $url | tee -a blh-light.txt; done ;
      - name: Send Output Files Slack Channel
        run: |
         cat blh-light.txt | grep -v "├───OK───" > blh-light-broken.txt
         zip blc-light.zip blh-light.txt blh-light-broken.txt
         curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Broken-Link-Checker-Light -F file=@blc-light.zip
