name: SubBrute
on:
  workflow_dispatch:
env:
     TARGET: ${{ secrets.DOMAIN }}
     S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
     S_URL: https://slack.com/api/files.upload
jobs:
  SubBrute:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo apt-get install python-dnspython -y;
         git clone https://github.com/TheRook/subbrute.git;
         wget https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt;
         xz -d wordlists/subdomains-1m-1.txt.xz;
      - name: SubBrute
        run: |
         python subbrute/subbrute.py -s subbrute/names.txt "$TARGET" -o subbrute.txt -r resolvers.txt -c 50
      - name: Slack
        if: always()
        run: |
         S_CHANNEL=$(echo $TARGET | sed 's/\./_/g');
         curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=SubBrute -F file=@subbrute.txt;
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK";
