name: SubBrute
on:
  workflow_dispatch:
env:
       TARGET: ${{ secrets.DOMAIN }}
       SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CN_SOLO }} 
       WEBHOOK: ${{ secrets.SLACK_WEBHOOK_SOLO }}
jobs:
  SubBrute:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         sudo apt-get install python-dnspython -y
         git clone https://github.com/TheRook/subbrute.git
         wget https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt
         xz -d wordlists/subdomains-1m-1.txt.xz;
      - name: SubBrute
        run: python subbrute/subbrute.py -s wordlists/subdomains-1m-1.txt "$TARGET" -o subbrute.txt -r resolvers.txt -c 50
      - name: Send Output to Slack
        if: always()
        run: curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-SubBrute-1 -F filename=subbrute-1.txt -F file=@subbrute.txt


  Slack-Notification:
   if: always()
   runs-on: ubuntu-latest
   needs: SubBrute
   steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        if: always()
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"SubBrute Bruteforce COMPLETED FOR - '$TARGET'"}' "$WEBHOOK"
