name: SubBrute
on:
  workflow_dispatch:
env:
     TARGET: ${{ secrets.DOMAIN }}
     S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
     S_URL: https://slack.com/api/files.upload
jobs:
  SubBrute:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: SubBrute
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials;
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/subbrute.sh "$TARGET";
      - name: Upload Artifacts                                                                                                                                                              
        if: always()                                                                                                                                                                        
        uses: actions/upload-artifact@v2                                                                                                                                                    
        with:
         name: Subbrute-artifacts
         path: subbrute.txt
      - name: Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHO$K"


  HTTPX:
    if: always()
    runs-on: ubuntu-latest
    needs: SubBrute
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: Subbrute-artifacts
      - name: HTTPX
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials;
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/httpx.sh subbrute.txt;                 
         cat httpx.out | cut -d "/" -f 3 > subs.subbrute;        
      - name: Slack
        if: always()
        run: |
         S_CHANNEL=$(echo $TARGET | sed 's/\./_/g');
         curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=SubBrute -F file=@subs.subbrute;
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK";
