name: Subdomain Recon
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      HOST: ${{ secrets.NGROK_URL }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }} 

jobs:
  Subdomain-enum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Subdomains
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         wget -q $HOST/subdomains-reliable.txt -O subdomains-manual.txt;
         GREEN='\033[0;32m'; cat subdomains-manual.txt | head | xargs -n1 echo -e ${GREEN} snipped;
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials;
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/subs.sh "$TARGET";
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: subdomains-artifacts
         path: all-subdomains.txt
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  HTTPX-1:
    needs: Subdomain-enum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: subdomains-artifacts    
      - name: Install Dependencies
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         GREEN='\033[0;32m'; cat all-subdomains.txt | head | xargs -n1 echo -e ${GREEN} snipped;
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials;
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/httpx.sh all-subdomains.txt;
         cat httpx.out | cut -d "/" -f 3 > all-subdomains-resolved.txt   
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: httpx-artifacts
         path: all-subdomains-resolved.txt
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  DNSgen:
    runs-on: ubuntu-latest
    needs: HTTPX-1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: httpx-artifacts
      - name: DNSgen
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         GREEN='\033[0;32m'; cat all-subdomains-resolved.txt | head | xargs -n1 echo -e ${GREEN} snipped;
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials;
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;       
         bash Domain_Monitoring/scripts/dnsgen.sh all-subdomains-resolved.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: dnsgen-artifacts
         path: |
          dnsgen-wordlist.txt.xz
          all-subdomains-resolved.txt
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  MassDNS:
    runs-on: ubuntu-latest
    needs: DNSgen
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: dnsgen-artifacts
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         xz -d dnsgen-wordlist.txt.xz;
         GREEN='\033[0;32m'; cat all-subdomains-resolved.txt | head | xargs -n1 echo -e ${GREEN} snipped;
         GREEN='\033[0;32m'; cat dnsgen-wordlist.txt | head | xargs -n1 echo -e ${GREEN} snipped;
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials;
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git   ;      
         bash Domain_Monitoring/scripts/massdns.sh "$TARGET";
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: dnsgen-artifacts
         path: |
          all-subdomains-resolved.txt
          subdomains.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  HTTPX-2:
    needs: MassDNS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: subdomains-artifacts    
      - name: Install Dependencies
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         xz -d subdomains.txt.xz;
         GREEN='\033[0;32m'; cat subdomains.txt | head | xargs -n1 echo -e ${GREEN} snipped;
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials;
         echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/httpx.sh subdomains.txt;
         cat httpx.out | cut -d "/" -f 3 > resolved-subdomains.txt;
         xz -k resolved-subdomains.txt;
      - name: Slack
        if: always()
        run: |
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="$TARGET"-MassDNS-Hosts -F file=@resolved-subdomains.txt.xz;
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;
