name: Subdomain Bruteforce Recon
on:
  workflow_dispatch:
env:
      TARGET: ${{ secrets.DOMAIN }}
      EXCLUDE_HOST: ${{ secrets.EXCLUDE_HOST }}
      S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
      WEBHOOK: ${{ secrets.WHOOK_JOB_ALERTS }}
      S_URL: https://slack.com/api/files.upload
      CUSTOM_GIT_CREDS : ${{ secrets.CUSTOM_GIT_CREDENTIALS }}
      CUSTOM_GIT_CONFIG : ${{ secrets.CUSTOM_GIT_CONFIG }} 

jobs:     
  MassDNS-1:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;   
         xz -d wordlists/subdomains-w{1..2}.txt.xz;
         cat wordlists/subdomains-w{1..2}.txt > subdomain-wordlists.txt;
         echo "[+] Wordlist count is `cat subdomain-wordlists.txt`"
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlists-temp.txt;
         cat wordlists-temp.txt | sed 's/\*\.//g' | sort -u > wordlists.txt;
         echo "[+] Wordlist count is `cat wordlists.txt`";
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/massdns.sh;
         cp hosts-massdns.txt hosts-massdns-1.txt;
         xz hosts-massdns-1.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: massdns-1-artifacts
         path: |
          hosts-massdns-1.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  MassDNS-2:
    if: always()
    runs-on: ubuntu-latest
    needs: MassDNS-1
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: massdns-1-artifacts
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;         
         xz -d wordlists/subdomains-1m-{1..13}.txt.xz;
         cat wordlists/subdomains-1m-{1..13}.txt > subdomain-wordlists.txt;
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlists-temp.txt;
         cat wordlists-temp.txt | sed 's/\*\.//g' | sort -u > wordlists.txt;
         echo "[+] Wordlist count is `cat wordlists.txt`";
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/massdns.sh;
         cp hosts-massdns.txt hosts-massdns-2.txt;
         xz hosts-massdns-2.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: massdns-2-artifacts
         path: |
          hosts-massdns-1.txt.xz
          hosts-massdns-2.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;


  MassDNS-3:
    if: always()
    runs-on: ubuntu-latest
    needs: MassDNS-2
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: massdns-2-artifacts
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;         
         FILE_DATE=$(date --date="$(date +%Y-%m-28) -1 month" +'%Y_%m_28');
         wget -q https://wordlists-cdn.assetnote.io/data/automated/httparchive_subdomains_"$FILE_DATE".txt;
         cat wordlists/bitquark-subdomains-top100000.txt httparchive_subdomains_"$FILE_DATE".txt > subdomain-wordlists.txt; 
         sort -u subdomain-wordlists.txt -o subdomain-wordlists.txt; 
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlist-temp.txt;
         cat wordlist-temp.txt | sed 's/\*\.//g' | sort -u > wordlists.txt;
         echo "[+] Wordlist count is `cat wordlists.txt`";
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/massdns.sh;
         cp hosts-massdns.txt hosts-massdns-3.txt;
         xz hosts-massdns-3.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: massdns-3-artifacts
         path: |
          hosts-massdns-1.txt.xz
          hosts-massdns-2.txt.xz
          hosts-massdns-3.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  MassDNS-4:
    if: always()
    runs-on: ubuntu-latest
    needs: MassDNS-3
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: massdns-3-artifacts
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;         
         wget -q https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt -O subdomain-wordlists.txt; 
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlist-temp.txt;
         cat wordlist-temp.txt | sed 's/\*\.//g' | sort -u > wordlists.txt;
         echo "[+] Wordlist count is `cat wordlists.txt`";
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/massdns.sh;
         cp hosts-massdns.txt hosts-massdns-4.txt;
         xz hosts-massdns-4.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: massdns-4-artifacts
         path: |
          hosts-massdns-1.txt.xz
          hosts-massdns-2.txt.xz
          hosts-massdns-3.txt.xz
          hosts-massdns-4.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;


  MassDNS-5:
    if: always()
    runs-on: ubuntu-latest
    needs: MassDNS-4
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: massdns-4-artifacts
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;         
         wget -q https://wordlists-cdn.assetnote.io/data/manual/2m-subdomains.txt -O subdomain-wordlists.txt; 
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlist-temp.txt;
         cat wordlist-temp.txt | sed 's/\*\.//g' | sort -u > wordlists.txt;
         echo "[+] Wordlist count is `cat wordlists.txt`";
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/massdns.sh;
         cp hosts-massdns.txt hosts-massdns-5.txt;
         xz hosts-massdns-5.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: massdns-5-artifacts
         path: |
          hosts-massdns-1.txt.xz
          hosts-massdns-2.txt.xz
          hosts-massdns-3.txt.xz
          hosts-massdns-4.txt.xz
          hosts-massdns-5.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  MassDNS-6:
    if: always()
    runs-on: ubuntu-latest
    needs: MassDNS-5
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: massdns-5-artifacts
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;         
         wget -q https://raw.githubusercontent.com/internetwache/CT_subdomains/master/top-100000.txt -O ct_top-100000.txt; cat ct_top-100000.txt | cut -d "," -f 2 > subdomain-wordlists.txt
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlist-temp.txt;
         cat wordlist-temp.txt | sed 's/\*\.//g' | sort -u > wordlists.txt;
         echo "[+] Wordlist count is `cat wordlists.txt`";
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/massdns.sh;
         cp hosts-massdns.txt hosts-massdns-6.txt;
         xz hosts-massdns-6.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: massdns-8-artifacts
         path: |
          hosts-massdns-1.txt.xz
          hosts-massdns-2.txt.xz
          hosts-massdns-3.txt.xz
          hosts-massdns-4.txt.xz
          hosts-massdns-5.txt.xz
          hosts-massdns-6.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  MassDNS-7:
    if: always()
    runs-on: ubuntu-latest
    needs: MassDNS-6
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: massdns-6-artifacts
      - name: MassDNS
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;         
         wget -q https://raw.githubusercontent.com/fuzz-security/SuperWordlist/master/SubDomain.txt -O subdomain-wordlists.txt;
         sed "s/$/.$TARGET/" subdomain-wordlists.txt > wordlist-temp.txt;
         cat wordlist-temp.txt | sed 's/\*\.//g' | sort -u > wordlists.txt;
         echo "[+] Wordlist count is `cat wordlists.txt`";
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/massdns.sh;
         cp hosts-massdns.txt hosts-massdns-7.txt;
         xz hosts-massdns-7.txt;
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: massdns-7-artifacts
         path: |
          hosts-massdns-1.txt.xz
          hosts-massdns-2.txt.xz
          hosts-massdns-3.txt.xz
          hosts-massdns-4.txt.xz
          hosts-massdns-5.txt.xz
          hosts-massdns-6.txt.xz
          hosts-massdns-7.txt.xz
      - name: Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;

  DNSx:
    runs-on: ubuntu-latest
    if: always()
    needs: MassDNS-7
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/download-artifact@v2
        with:
         name: massdns-7-artifacts
      - name: DNSx
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         echo "$EXCLUDE_HOST" > exclude-host.txt;
         xz -d hosts-massdns-{1..7}.txt.xz; cat hosts-massdns-{1..7}.txt > hosts-massdns-temp.txt; 
         cat hosts-massdns-temp.txt | sed 's/\*\.//g' > subdomains-temp-2.txt;
         sort -u subdomains-temp-2.txt -o subdomains-temp-2.txt;
         grep -vFf exclude-host.txt subdomains-temp-2.txt > hosts-massdns.txt;
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/dnsx.sh hosts-massdns.txt;
         mv dnsx.txt dnsx-brute.txt; mv hosts-live.txt brute-hosts-live.txt; mv ips-live.txt brute-ips-live.txt;
         xz -k dnsx-brute.txt brute-hosts-live.txt brute-ips-live.txt;
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
         name: dnsx-artifacts
         path: |
          brute-hosts-live.txt.xz
      - name: Slack Notification
        if: always()
        run: |
          S_CHANNEL=$(echo $TARGET | sed 's/\./_/g');
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=DNSx-Brute -F file=@dnsx-brute.txt.xz;
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=DNSx-Brute-Hosts-Live -F file=@brute-hosts-live.txt.xz;
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=DNSx-Brute-IPs-Live -F file=@brute-ips-live.txt.xz;
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;


  HTTPX:
    if: always()
    needs: DNSx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
         name: dnsx-artifacts    
      - name: Install Dependencies
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`Started`*_  - '$TARGET'"}' "$WEBHOOK";
         echo "$CUSTOM_GIT_CREDS" > ~/.git-credentials; echo "$CUSTOM_GIT_CONFIG" > ~/.gitconfig;
         xz -d brute-hosts-live.txt.xz
         git clone https://github.com/ValluvarSploit/Domain_Monitoring.git;
         bash Domain_Monitoring/scripts/httpx.sh brute-hosts-live.txt light;
         cp httpx.out httpx-brute-resolved-url.txt;
         cat httpx-brute-resolved-url.txt | cut -d "/" -f 3 > httpx-brute-resolved-host.txt;
         xz httpx-brute-resolved-url.txt httpx-brute-resolved-host.txt;
      - name: Slack
        if: always()
        run: |
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=HTTPX-Brute-URL -F file=@httpx-brute-resolved-url.txt.xz;
          curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title=HTTPX-Brute-Host -F file=@httpx-brute-resolved-host.txt.xz;
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_  - '$TARGET'"}' "$WEBHOOK" ;
