#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. DOMAIN
#       example.com


name: Subdomain Bruteforce
on:
  workflow_dispatch:
env:
     TARGET_DOMAIN: ${{ secrets.DOMAIN }} 
     TARGET_SUBDOMAINS: ${{ secrets.DOMAIN_SUBDOMAINS_HTTPS }}
     SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     SLACK_CHANNEL_NAME: ${{ secrets.SLACK_PRIVATE_BB_CHANNEL_NAME }}

jobs:
  subdomain bruteforce:
    runs-on: ubuntu-latest          
    steps:
      - uses: actions/checkout@v2
      - name: Input Files
        run: sed "s/$/.$TARGET_DOMAIN/" wordlists/subdomain-wordlists.txt > wordlist.txt
      - name: Install Dependencies
        run: |
         wget --quiet https://raw.githubusercontent.com/ValluvarSploit/Resolver/main/resolvers.txt
         git clone https://github.com/blechschmidt/massdns.git && cd massdns/ && make
         wget https://github.com/projectdiscovery/httpx/releases/download/v1.0.3/httpx_1.0.3_linux_amd64.tar.gz && tar -xvf httpx_1.0.3_linux_amd64.tar.gz

      - name: DNS Resolver-MassDNS
        run: |
         ./massdns/bin/massdns -r resolvers.txt -t A -o S -w massdns-output.txt wordlist.txt
         cat massdns-output.txt | awk '{print $1}' | sed 's/.$//' | tr A-Z a-z | sort -u > live-hosts.txt
         cat massdns-output.txt | awk '{print $3}' | sort -u | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" > live-ips.txt 
         ./httpx -l live-hosts.txt -o resolved.txt -threads 500 -silent -stats
        
  
