name: Subdomain Takeover

on:
  workflow_dispatch:

jobs:       
  subdomain-takeover:
    runs-on: ubuntu-latest
    env:
      INPUT_FILE: '/home/runner/work/Test-Data/Test-Data/live-httpx-subdomains-output.txt'
      CURRENT_DIRECTORY: pwd
  
    steps:
      - uses: actions/checkout@v2
        
      # subzy, subjack, nuclei
      - name: test
        run: echo "$CURRENT_DIRECTORY"
      - name: Install Dependencies
        run: |
         go get -u -v github.com/lukasikic/subzy
         go get -v github.com/haccer/subjack
         git clone https://github.com/projectdiscovery/nuclei-templates.git
         wget https://github.com/projectdiscovery/nuclei/releases/download/v2.2.0/nuclei_2.2.0_linux_amd64.tar.gz
         tar -xzvf nuclei_2.2.0_linux_amd64.tar.gz
      - name: Subzy
        run: |
         cd /home/runner/go/bin/
         ./subzy --targets="$INPUT_FILE" -concurrency 50 -hide_fails | tee /home/runner/work/Test-Data/Test-Data/subdomain-takeover-output.txt
      - name: Subjack
        run: |
         cd /home/runner/go/bin/
         ./subjack -w "$INPUT_FILE" -t 100 -timeout 30 -o /home/runner/work/Test-Data/Test-Data/subjack-output.txt -ssl -c /home/runner/go/src/github.com/haccer/subjack/fingerprints.json
         cd /home/runner/work/Test-Data/Test-Data/
         if [[ ! -f subjack-output.txt ]]; then touch subjack-output.txt; fi
      - name: Nuclei
        run: |
         ./nuclei -l "$INPUT_FILE" -c 100 -stats -t nuclei-templates/subdomain-takeover/ -o nuclie-output.txt
         if [[ ! -f nuclie-output.txt ]]; then touch nuclie-output.txt; fi
      - name: Combine Outputs
        run: |
         cat subjack-output.txt | tee -a subdomain-takeover-output.txt
         cat nuclie-output.txt | tee -a subdomain-takeover-output.txt
      - name: Remove Temporary Files
        run: |
          rm LICENSE.md nuclei README.md nuclei_2.2.0_linux_amd64.tar.gz subjack-output.txt nuclie-output.txt
          rm -rf nuclei-templates/
      - name: Commit Tool Output
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add subdomain-takeover-output.txt
          git commit -m "Update subdomain-takeover-output.txt"
          git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags
