name: Subsmasher
on:
  workflow_dispatch:
env:
   HOST: ${{ secrets.NGROK_URL }}
   SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
   SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}

jobs:  
  subsmasher:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
         git clone https://github.com/ValluvarSploit/SubWalker.git
         cd subwalker; chmod +x install.sh subwalker.sh; sudo ./install.sh
      - name: Subsmasher
        run: ./subwalker.sh 
      - name: Send Output to Slack
        run: |
        #curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Nmap-UDP-Scan -F filename=nmap-udp-scan.xml -F file=@nmap-udp-scan.xml
        #curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title=Nmap-UDP-Scan -F filename=nmap-udp-scan.nmap -F file=@nmap-udp-scan.nmap
