name: Test CI
 
on:

  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
                 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
                 TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }} 
                 TARGET_IGNORE_HOSTS: $ {{ secrets.TARGET_IGNORE_HOSTS_LIST }}
                 TARGET_IGNORE_IPS: $ {{ secrets.TARGET_IGNORE_IPS_LIST }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Run Test Script
        run: |
                 echo "$TARGET_DOMAIN_Bingo"
                 echo "$TARGET_DOMAIN"_Dingo
                 FILE_NAME="$TARGET_DOMAIN"_Jingo
                 echo "$FILE_NAME" > file.txt
                 curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="Test-Data tools subdomain file-$today" -F filename="$TARGET_DOMAIN"_subdomains-tools-output_$today.txt -F file=@file.txt
                 


