name: Test CI
 
on:

  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
               HOSTS_LIST: ${{ secrets.TARGET_HOSTS_LIST }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Run Test Script
        run: |
                 pip3 install dnsgen
                 ls -l ~/.local/bin/dnsgen
                 cd ~/.local/bin/
                 ./dnsgen --help

