name: Test CI
 
on:

  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
                 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
                 TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }} 
                 TARGET_IGNORE_HOSTS: $ {{ secrets.TARGET_IGNORE_HOSTS_LIST }}
                 TARGET_IGNORE_IPS: $ {{ secrets.TARGET_IGNORE_IPS_LIST }}
                 DATE: $(date +"%d_%m_%Y")
                 FILE_NAME: "$TARGET_DOMAIN"
    
    steps:
      - uses: actions/checkout@v2

      - name: Run Test Script
        run: |
                 echo "$DATE"
                 echo "$FILE_NAME"
                 


