name: My TestCI
 
on:
  workflow_dispatch:

jobs:
  nmap-1000-ports-scan:
    runs-on: ubuntu-latest
    env:
                 TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
                 TARGET_IP: ${{ secrets.TARGET_IP_LIST }}
                 TARGET_IP_EXCLUDE: ${{ secrets.TARGET_IGNORE_IPS_LIST }}
                 SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
                 SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}  
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
                 echo "Hello World"
