name: URL Collector

on:
  workflow_dispatch:

jobs:
  url-collector:
    runs-on: ubuntu-latest
    env:
            TARGET_DOMAIN: ${{ secrets.TARGET_DOMAIN }}
 
    steps:
      - uses: actions/checkout@v2
        
      - name: Tools Installation and Setup
        run: |
                 go get -u github.com/tomnomnom/gf
                 git clone https://github.com/1ndianl33t/Gf-Patterns
                 mkdir ~/.gf
                 cp -r Gf-Patterns/*.json ~/.gf/
                 wget --quiet https://github.com/tomnomnom/qsreplace/releases/download/v0.0.1/qsreplace-linux-386-0.0.1.tgz
                 tar xvf qsreplace-linux-386-0.0.1.tgz
#                go get github.com/tomnomnom/waybackurls
#                wget --quiet https://github.com/lc/gau/releases/download/v1.1.0/gau_1.1.0_linux_amd64.tar.gz
#                tar xvf gau_1.1.0_linux_amd64.tar.gz
                
                
      - name: Remove Old files
        run: |
                 rm sqli-params.txt
#                rm urls-output.txt.zip.xz urls-output.txt rm xss-params.txt

      - name: waybackurls
        run: |
#                cd /home/runner/go/bin/
#                ./waybackurls "$TARGET_DOMAIN" | tee temp-1.txt | grep "=" | egrep -iv ".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)" | tee /home/runner/work/Test-Data/Test-Data/waybackurls-output.txt

      - name: gau
        run: |
#                echo "$TARGET_DOMAIN" | ./gau | tee temp-2.txt | grep "=" | egrep -iv ".(jpg|jpeg|gif|css|tif|tiff|png|ttf|woff|woff2|ico|pdf|svg|txt|js)" | tee gau-output.txt
                
      - name: Combine Output Files
        run: |
#                 cat urls-output.txt | ./qsreplace FUZZ | tee -a unique-url-output.txt
#                cat waybackurls-output.txt gau-output.txt | tee urls-output.txt
#                sort -u urls-output.txt -o urls-output.txt
                
#      - name: XSS Pattern
#        run: |
#                cd /home/runner/go/bin/
#                cat /home/runner/work/Test-Data/Test-Data/unique-url-output.txt | ./gf xss | tee -a /home/runner/work/Test-Data/Test-Data/xss-params.txt
                
      - name: SQLi Pattern
        run: |
                cd /home/runner/go/bin/
                cat /home/runner/work/Test-Data/Test-Data/unique-url-output.txt | ./gf sqli | tee -a /home/runner/work/Test-Data/Test-Data/sqli-params.txt          
                
      - name: Compress Output File
        run: |
#              ls -lh
#               zip urls-output.txt.zip urls-output.txt
#              xz urls-output.txt.zip
#              ls -lh
#                xz -d urls-output.txt.zip.xz
#                unzip urls-output.txt.zip

      - name: Remove Installation Files
        run: |
                 rm qsreplace-linux-386-0.0.1.tgz
#                rm LICENSE README.md gau gau_1.1.0_linux_amd64.tar.gz temp-2.txt waybackurls-output.txt gau-output.txt
                 
      - name: Commit Tool Output
        run: |
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"
                git add sqli-params.txt
                git commit -m "Update urls-output.txt.zip.xz"
                git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags
#unique-url-output.txt xss-params.txt
