name: Webshot

on:
  workflow_dispatch:

jobs:
  screenshot-eyewitness:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tools Installation and Setup
        run: |
          git clone https://github.com/FortyNorthSecurity/EyeWitness.git
          cd EyeWitness/Python/setup
          sudo ./setup.sh
      - name: Remove Old files
        run: rm eyewitness_output.zip.xz
      - name: Eyewitness
        run: |
          python3 EyeWitness/Python/EyeWitness.py --web -f test.txt --timeout 15 --no-prompt
          ls -l 2020*
          mv `date +"%Y"`* eyewitness_output
          ls -lh eyewitness_output/
          zip eyewitness_output.zip eyewitness_output
          ls -lh eyewitness_output.zip
          xz eyewitness_output.zip
          ls -lh eyewitness_output.zip.xz
          rm -rf eyewitness_output
      - name: Final Clean-up
        run: |
          rm geckodriver.log
          rm -rf EyeWitness
      - name: Commit Tool Output
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add eyewitness_output.zip.xz
          git commit -m "Update Eyewitness Output"
          git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags
