name: Webshot

on:
  workflow_dispatch:

jobs:
  webshot-eyewitness:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tools Installation and Setup
        run: |
          git clone https://github.com/FortyNorthSecurity/EyeWitness.git
          cd EyeWitness/Python/setup
          sudo ./setup.sh
      - name: Remove Old files
        run: rm eyewitness_output.zip.xz
      - name: Eyewitness
        run: |
          python3 EyeWitness/Python/EyeWitness.py --web -f live-httpx-subdomains-output.txt --proxy-ip 127.0.0.1 --proxy-port 8080 --proxy-type socks5 --timeout 120 --no-prompt
          mv `date +"%Y"`* eyewitness_output
          zip -r eyewitness_output.zip eyewitness_output
          xz eyewitness_output.zip
          rm -rf eyewitness_output
      - name: Final Clean-up
        run: |
          rm geckodriver.log
          rm -rf EyeWitness
      - name: Commit Tool Output
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add eyewitness_output.zip.xz
          git commit -m "Update Eyewitness Output"
          git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags
