#Important Note:
# Before running this action, make sure you updated following secrets variables in settings.
#  1. TARGET_DOMAIN
#       example.com
name: XSS Hunter
on:
  workflow_dispatch:
env:
     TARGET_DOMAIN: ${{ secrets.PRI_LARGE_DOMAIN }}
     SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
     SLACK_CHANNEL_NAME: ${{ secrets.SLACK_CHANNEL_NAME }}
     XSS_HUNTER_TOKEN: ${{ secrets.XSS_HUNTER }}
jobs:               
  xss-hunter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2       
      - name: Install Dependencies
        run: |
         wget $HOST/xss-parameter.txt
         sudo snap install dalfox       
      - name: Dalfox
        run: dalfox -b "$XSS_HUNTER_URL_TOKEN" file xss-parameter.txt > xss-vulnerable-urls.txt
      - name: Send Outputs to Slack
        run: |
         if [[ -f xss-vulnerable-urls.txt ]] ; then curl https://slack.com/api/files.upload -F token="$SLACK_OAUTH_TOKEN" -F channels="$SLACK_CHANNEL_NAME" -F title="$TARGET"-XSS -F filename=xss-vulnerable-urls.txt -F file=@xss-vulnerable-urls.txt; fi
