name: XSS Hunter

on:
  workflow_dispatch:

jobs:
  xss-hunter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
                go get -u github.com/tomnomnom/hacks/kxss
                sudo snap install dalfox
                
      - name: Remove Exisiting Output Files
        run: |
                rm xss-output.txt
                
      - name: KXSS
        run: |
                cd /home/runner/go/bin/
                cat /home/runner/work/Test-Data/Test-Data/urls-output.txt | ./kxss | awk '{print $9}' > tee /home/runner/work/Test-Data/Test-Data/xss-urls.txt
                    
      - name: Dalfox  
        run: |
                cat xss-urls.txt | dalfox pipe -b https://alexdeveloper.xss.ht | tee -a xss-output.txt
             
      - name: Commit Tool Output
        run: |
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"
                git add xss-output.txt xss-urls.txt
                git commit -m "XSS-Update Output Files"
                git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Test-Data.git" HEAD:main --follow-tags 
